steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/services/{{.ServiceName}}:$_VERSION',
            '--cache-from', 'gcr.io/$PROJECT_ID/services/{{.ServiceName}}:latest',
            '--file', './services/{{.ServiceName}}/Dockerfile.prod',
            '.'
        ]
images: ['gcr.io/$PROJECT_ID/services/{{.ServiceName}}:$_VERSION']
