name: {{.ServiceName}}
test-command: go test .
check-command: go vet .
gen-proto-command: protoc --go_out=. --twirp_out=. -I={{.ProjectDir}} -I=$GOPATH/src {{.ServicesDir}}/{{.ServiceName}}/proto/service.proto
include:
  - go.mod
  - go.sum
