name: {{.ServiceName}}
test-command: go test .
check-command: go vet .
gen-proto-command: protoc --go_out=. --twirp_out=. -I=$SYNTHWAVE_DIR -I=$GOPATH/src ${{.ServicesDir}}/{{.ServiceName}}/proto/.proto
include:
  - go.mod
  - go.sum
